/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/verify`; params?: Router.UnknownInputParams; } | { pathname: `/../../web-admin/app/dashboard/shifts/page`; params?: Router.UnknownInputParams; } | { pathname: `/my-shifts`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/gateway/shifts.gateway`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/gateway/gateway.module`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/notifications/notifications.service`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/notifications/processors/re-notification.processor`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/notifications/notifications.module`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/socket`; params?: Router.UnknownInputParams; } | { pathname: `/../../web-admin/lib/socket`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/shift/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/verify`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web-admin/app/dashboard/shifts/page`; params?: Router.UnknownOutputParams; } | { pathname: `/my-shifts`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/gateway/shifts.gateway`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/gateway/gateway.module`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/notifications/notifications.service`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/notifications/processors/re-notification.processor`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/notifications/notifications.module`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/socket`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web-admin/lib/socket`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/shift/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/verify${`?${string}` | `#${string}` | ''}` | `/../../web-admin/app/dashboard/shifts/page${`?${string}` | `#${string}` | ''}` | `/my-shifts${`?${string}` | `#${string}` | ''}` | `/../../api/src/gateway/shifts.gateway${`?${string}` | `#${string}` | ''}` | `/../../api/src/gateway/gateway.module${`?${string}` | `#${string}` | ''}` | `/../../api/src/notifications/notifications.service${`?${string}` | `#${string}` | ''}` | `/../../api/src/notifications/processors/re-notification.processor${`?${string}` | `#${string}` | ''}` | `/../../api/src/notifications/notifications.module${`?${string}` | `#${string}` | ''}` | `/../lib/socket${`?${string}` | `#${string}` | ''}` | `/../../web-admin/lib/socket${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/verify`; params?: Router.UnknownInputParams; } | { pathname: `/../../web-admin/app/dashboard/shifts/page`; params?: Router.UnknownInputParams; } | { pathname: `/my-shifts`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/gateway/shifts.gateway`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/gateway/gateway.module`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/notifications/notifications.service`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/notifications/processors/re-notification.processor`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/notifications/notifications.module`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/socket`; params?: Router.UnknownInputParams; } | { pathname: `/../../web-admin/lib/socket`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/shift/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/shift/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
